bucket.go

Partially fixes https://github.com/couchbase/sync_gateway/issues/1710

Expose Refresh() method to support lost TAP feed recovery

---

collate.go

ViewResult key values arriving as uint16 were getting rejected by collator.

Add uint16 support to collator

---

collate.go

Needed to support upgrade to latest otto in sync_gateway this is part of the fix for https://github.com/couchbase/sync_gateway/issues/2471

Handle case where walrus bucket returns []float64 instead of []interface{}

---

bucket.go
views.go

Required for GSI support.
Includes QueryResultsIterator interface definition, and implementation for the existing ViewResults.

Add ViewQuery to bucket interface

---

views.go

Adds support for 'keys' to the sg-bucket view post-processing (ProcessViewResult).  Aligns with Couchbase Server parameter, needed for https://github.com/couchbase/sync_gateway/issues/3823

Adds support for view 'keys' parameter

---

tap.go

Supports unique naming when running multiple DCP feeds in a single process.

Add feed ID to FeedArguments

---

bucket.go
tap.go

Previously used for tap feed handling, no longer used for DCP.
Unused references removed from SG in https://github.com/couchbase/sync_gateway/pull/4247

Remove BucketNotifyFn

---

bucket.go
views.go

- Renames Bucket to DataStore in anticipation of collection support
- Split bucket interface into functional sub-interfaces
- Remove unused APIs (GetBulkRaw, Append, Write, SetBulk)

Bucket interface refactoring

---

bucket.go

WriteUpdate is legacy from go-couchbase's integration.  Update serves the same purpose today, and WriteOpts aren't being used.

Remove WriteUpdate from bucket interface

---

tap.go

Changes to include DoneChan channel in FeedArguments to signal on mutation feed termination.

CBG-1217 Include DoneChan channel in FeedArguments to signal on mutation feed termination

---

bucket.go

2.8.1 backport of #59 - Required change due to the change in the way we handle Features for 3.0

[2.8.1 Backport] CBG-1200: Added new DataStoreFeature (#59)

---

tap.go

[CBG-1763](https://issues.couchbase.com/browse/CBG-1763)
Added a Group ID field to the `FeedArguments` struct, which will be filled on Sync Gateway so the DCP feed code can use it.

CBG-1763: Added Group ID field to FeedArguments

---

bucket.go

Just adds the subdoc operations: `GetSubDocRaw` and `WriteSubDoc`

CBG-1837: Adding subdoc operations

---

bucket.go

Added new Upsert Options to KV `Set` and `SetRaw` operations
Added new Mutations options to XattrStore `WriteUpdateWithXattr`

CBG-1563: Use preserveExpiry during document import

---

js_map_fn.go
js_map_fn_test.go
js_runner.go
js_server.go

CBG-2145 - Part of PR https://github.com/couchbase/sync_gateway/pull/5639
- Adds timeout to Otto running JS function
- Adding timeout to `SetFunction` function in `JSServerTask` interface
- Using `JSServer` function to return timeout along with function

CBG-2145: Added Javascript timeout option

---

js_runner.go

Needed for user JS functions and GraphQL resolvers. In these, the entire HTTP request has a timeout, so the time available to a single JS function is variable.

Added JSRunner.SetTimeout()

---

tap.go

Revert "CBG-1143 add started channel for notification when DCP is ready (#76)"
This reverts commit 29ae27b3d9d06086e2a04a9a8bc9319e7b693f45.

CBG-2233 remove unused channel

---

tap.go

Reverts couchbase/sg-bucket#79, as it's no longer necessary in the corresponding SG PR (https://github.com/couchbase/sync_gateway/pull/5719)

Revert "CBG-2344: Add FeedOpExpiration"

---

bucket.go

- `BucketStore` now describes something that can return one or more DataStores (i.e. Collections) and has bucket-level operations (`MutationFeedStore`, `BucketStoreFeature` capabilities)
- `DataStore` describes a basic data store that supports KV/Xattr/Subdoc
- Smaller interfaces for `KVStore` and `SubDocStore` that individual DataStores can implement
- `BucketStore` implementations can also implement `DynamicDataStoreBucket` which describes methods for creating and removing DataStores within a bucket (useful for testing purposes)

Narrow DataStore interface and add BucketStore

---

js_runner.go

CBG-2276
A small optimisation for when running without a timeout set.
Leaving timeout logic in, but opting out of it on the SG side in https://github.com/couchbase/sync_gateway/pull/6004 for sync, import and conflict resolver functions (some of Jens' graphql work uses this JS timeout functionality)

CBG-2276: Avoid channel allocation if no timeout is used

---

.github/workflows/ci.yml
.golangci.yml
collate_test.go
design_doc.go
go.mod
go.sum
js_runner.go
logg.go

- use go 1.19 to match sync gateway
- run go.mod tidy
- use .golangci.yml from sync gateway
- add golangci, race detector to github actions
- fixed lint errors (small ineffectual assignments, json tag issue)

CBG-2671 update to go.19

---

bucket.go
tap.go

Add contexts for logging.
I made the arbitrary decision to pass context as first parameter rather than adding as a feed argument because that is closer to a go idiom, and it forces the caller to make a decision.

CBG-1981 add contexts

---

bucket.go

The CB Server implementation of the system collection capability is just going to be `>= 7.6`

Add BucketStoreFeatureSystemCollections

---

bucket.go

Small change to add a alias of mutate in options to sg-bucket. sg-bucket is a shared libray between sync gateway and rosmar so makes it convenient place to add this functionality.
Step trough changes:
1. MutateInSpec: simple path value struct for purpose of providing xattr path and a value to be upserted into that path 
2. MutateInOptions: change to add a list of the above specs to the options (this struct is passed down the stack in crud operations in sync gateway and rosmar)
3. UpsertSpec: helper function to create this spec by just passing the value and path to it (much like the function in gocb of the same name)

changes needed in sg-bucket for macro expansion support to rosmar

---

.github/workflows/ci.yml
bucket.go
js_map_fn.go
js_map_fn_test.go
js_runner.go
js_server.go
licenses/addlicense.tmpl
views.go

This is a backport of https://github.com/couchbase/sg-bucket/pull/105. It had to be redone because of rosmar changes and changes to javascript interfaces.

[3.1.2 backport] CBG-3379 add contexts for log information

---

bucket.go

CBG-3448
We need to to able to update these mutate in options based off logic performed on the HLV. This provides a change to allow us to perform this logic in callback functions used in sync gateway. 
Exact change is having the already defined mutate in options passed into the functions and have the updated mutate in options returned out of the function.

CBG-3448: update WriteUpdateWithXattrFunc definition

---

bucket.go
tap.go

Add `UserXattrStore` to `DataStore` since rosmar supports this feature.
Unrelatedly, also add a new feature for mobile XDCR (available in 7.6.1) and a string debugging for DCP events.

Add UserXattrStore to DataStore to avoid type casts

---

bucket.go

Update APIs to support multiple xattrs. Create a new feature `BucketStoreFeatureMultiXattrSubdocOperations` to mark when writing multiple xattrs in one operation works (Couchbase Server 7.6.0)

CBG-3764 multi-xattr API support

---

bucket.go
tap.go

- Drop MutationFeedStore2 since the only implementations used by gocb and rosmar are DCP
- Merged DataStoreName (ScopeName(),CollectionName()) into DataStore, and add CollectionID to DataStore

Simplify interfaces to have fewer casts

---

tap.go
tap_test.go

- return in the case that xattrsLen is bigger than the data
- allow for xattr to have a nil value

CBG-3913 put fixes from sync_gateway into DecodeValueWithXattrs

---

tap.go
tap_test.go

Used for DCP-based purge in SGW test harness.

Add DecodeXattrNames for efficient retrieval of names only from DCP event value

---

js_runner.go

Call `SetStackDepthLimit` on the Otto js vm with a value of 10,000
The value 10,000 aligns with the maximum depth of Go's stdlib JSON library (golang/go#31789)
which is a good match for the worst-case of users recursing into nested document properties

Set Otto stack depth limit
