bucket.go
Uptake of GetAndTouch in SG bucket.
=> Adds support for GetAndTouch

tap.go
https://github.com/couchbase/sync_gateway/issues/1087
=> Add WriteEvents()

design_doc.go, views.go
This includes the code here https://github.com/couchbase/sg-bucket/pull/3
Both these changes are needed for a pull request I'm making to Sync Gateway.
=> Two features needed for SG pull req

views.go
This fixes https://github.com/couchbase/sync_gateway/issues/1188 but brings up the fact that our tests for this are not in this repo.
=> type conversion for view limit params

bucket.go
https://github.com/couchbase/sync_gateway/issues/1247
=> Add SetBulk

bucket.go, logg.go, tap.go
Part of fix for SG feature/issue sg 1319
=> Fixes for race conditions when building sync Gateway with test -race flag

bucket.go
=> Adds base set of XATTR operations to sgbucket

bucket.go, tap.go
Required for https://github.com/couchbase/sync_gateway/issues/2485
=> Add cas to tap event, WriteUpdateWithAttr callback

bucket.go
Also adds deleted flag to WriteUpdateWithXattrFunc callback.
=> Adds remove to bucket API

bucket.go
Related to https://github.com/couchbase/sync_gateway/issues/2423
=> Add GetStatsVbSeqno

design_doc.go
Required for https://github.com/couchbase/sync_gateway/pull/2668
=> Add flag to track whether design doc should index tombstones

bucket.go
Also adds ability to set expiry during Update/WriteUpdate
=> Standardize bucket API to use uint32 for expiry

tap.go
Companion PR to https://github.com/couchbase/sync_gateway/pull/3459
=> Remove field.Sequence

bucket.go
Companion PR for https://github.com/couchbase/sync_gateway/pull/4493
=> CBG-625 - Add GetDDocs to bucket interface

views.go
Previously only uint64 values were being converted to int - all others (including int) were ignored.
=> Fix for view limit type conversion

bucket.go
Cleans up DDoc API, removes ViewCustom.
=> Update View API, add typed dataStore errors

bucket.go
New feature to detect whether `SubdocDocFlagCreateAsDeleted` subdoc flag is supported
=> CBG-1200: Added new DataStoreFeature

bucket.go
Add subdoc operation data store feature and added subdoc insert op
=> CBG-1443: Add subdoc insert op

tap.go
Required for https://github.com/couchbase/sync_gateway/pull/5719.
=> CBG-2344: Add FeedOpExpiration

bucket.go
Moves XattrStore2 methods into XattrStore.
=> Consolidate XattrStore and XattrStore2

.github/workflows/ci.yml
Using new checkout and setup-go allows caching.
=> Update main branch and update ci for newer versions

bucket.go
This is part of a sync gateway and rosmar change.
=> CBG-3271 add context to CloseAndDelete to match Close

.github/workflows/ci.yml
update go version to match sync gateway
=> Update versions of actions to avoid warnings about node16

bucket.go
only rosmar using `MissingError` and while I think it would be optimal for sync gateway to wrap it's DocNotFoundErrors in a `MissingError` I think it's out of scope for this PR.
=> CBG-3921 consolidate error handling function to IsDocNotFoundError
